version: "3.1"
services:
  app:
    image: "h5p-lti_img"
    container_name: h5p-lti-provider
    working_dir: /home/node/app/h5p-nodejs-library
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    networks:
      - myinternal
    env_file: ./provider/.env
    build:
      context: ./provider
      dockerfile: Dockerfile
    command: npm run start
    #keep container running
    tty: true
    stdin_open: true

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
       - 'redis_data_container:/data'
    networks:
      - myinternal

  mongodb:
    image: "mongodb/mongodb-community-server:latest"
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_INITDB_DATABASE: ${MONGODB_DB}
    volumes:
       - 'mongodb_data_container:/data/db'
    networks:
      - myinternal

volumes:
  redis_data_container:
  mongodb_data_container:

networks:
  myinternal:
